name: Lint and Format

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Ruff and Black
        run: |
          pip install ruff black
      - name: Lint with ruff
        run: |
            CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '\.py$' || true)
            if [ -n "$CHANGED" ]; then
              ruff check $CHANGED
            else
              echo "No Python files changed."
            fi
        continue-on-error: true
      - name: Check formatting with Black
        run: black --check .
        continue-on-error: true
